name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        run: |
          git config --global user.email "docs@buildbuddy.io"
          git config --global user.name "BuildBuddy Docs Bot"
          yarn install && GIT_USER=siggisim GIT_PASS=${PAT} yarn deploy