name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        run: |
          git config --global user.email "siggisim@gmail.com"
          git config --global user.name "BuildBuddy Docs Bot"
          echo "machine github.com login siggisim password ${PAT}" > ~/.netrc
          yarn install && GIT_USER=siggisim yarn deploy